insert into ad (`id`,`spot_id`,`ad_type`,`industry_type`, `content`,`company`, `ddl`,`picture`,`remark`, `isdroped`) values
(1, 60, 'Floor Graphics', 'Technology and Electronics', 'sample data', 'Alphabet', '2026/04/10', 'default/not-found.png', '', 0), 
(2, 69, 'Sponsored Maps', 'Telecommunications', 'sample data', 'AT&T', '2029/08/14', 'default/not-found.png', '', 0), 
(3, 49, 'Floor Graphics', 'Energy and Utilities', 'sample data', 'Saudi Aramco', '2030/01/22', 'default/not-found.png', '', 0), 
(4, 17, 'Floor Graphics', 'Entertainment and Media', 'sample data', 'Netflix', '2029/04/17', 'default/not-found.png', '', 0), 
(5, 41, 'Floor Graphics', 'Aerospace and Defense', 'sample data', 'Boeing', '2026/05/09', 'default/not-found.png', '', 0), 
(6, 29, 'Interactive Displays', 'Healthcare and Pharmaceuticals', 'sample data', 'Johnson & Johnson', '2021/11/12', 'default/not-found.png', '', 0), 
(7, 21, 'Overhead Panels', 'Entertainment and Media', 'sample data', 'Walt Disney Company', '2024/09/17', 'default/not-found.png', '', 0), 
(8, 63, 'Sponsored Maps', 'Healthcare and Pharmaceuticals', 'sample data', 'Roche', '2028/11/12', 'default/not-found.png', '', 0), 
(9, 12, 'Overhead Panels', 'Healthcare and Pharmaceuticals', 'sample data', 'Roche', '2023/09/22', 'default/not-found.png', '', 0), 
(10, 38, 'Sponsored Maps', 'Entertainment and Media', 'sample data', 'Walt Disney Company', '2025/07/08', 'default/not-found.png', '', 0), 
(11, 35, 'Window Graphics', 'Entertainment and Media', 'sample data', 'Walt Disney Company', '2023/02/05', 'default/not-found.png', '', 0), 
(12, 11, 'Floor Graphics', 'Healthcare and Pharmaceuticals', 'sample data', 'Pfizer', '2020/10/02', 'default/not-found.png', '', 0), 
(13, 13, 'Overhead Panels', 'Energy and Utilities', 'sample data', 'Saudi Aramco', '2023/09/01', 'default/not-found.png', '', 0), 
(14, 56, 'Ceiling Ads', 'Telecommunications', 'sample data', 'Verizon ', '2028/11/17', 'default/not-found.png', '', 0), 
(15, 89, 'Ceiling Ads', 'Food and Beverage', 'sample data', 'McDonald', '2027/03/03', 'default/not-found.png', '', 0), 
(16, 80, 'Ceiling Ads', 'Aerospace and Defense', 'sample data', 'Boeing', '2029/11/23', 'default/not-found.png', '', 0), 
(17, 87, 'Interactive Displays', 'Food and Beverage', 'sample data', 'PepsiCo', '2021/09/27', 'default/not-found.png', '', 0), 
(18, 16, 'Digital Screens', 'Retail and Consumer Goods', 'sample data', 'The Procter & Gamble Company', '2027/03/11', 'default/not-found.png', '', 0), 
(20, 2, 'Floor Graphics', 'Healthcare and Pharmaceuticals', 'sample data', 'Johnson & Johnson', '2024/10/12', 'default/not-found.png', '', 0), 
(21, 91, 'Overhead Panels', 'Automotive and Transportation', 'sample data', 'Toyota', '2026/03/12', 'default/not-found.png', '', 0), 
(22, 46, 'Branded Seats', 'Energy and Utilities', 'sample data', 'Saudi Aramco', '2030/03/31', 'default/not-found.png', '', 0), 
(23, 24, 'Branded Seats', 'Automotive and Transportation', 'sample data', 'Honda', '2029/11/16', 'default/not-found.png', '', 0), 
(24, 74, 'Floor Graphics', 'Healthcare and Pharmaceuticals', 'sample data', 'Roche', '2020/02/25', 'default/not-found.png', '', 0), 
(25, 83, 'Interactive Displays', 'Healthcare and Pharmaceuticals', 'sample data', 'Johnson & Johnson', '2030/12/08', 'default/not-found.png', '', 0), 
(27, 100, 'Overhead Panels', 'Finance and Banking', 'sample data', 'Bank of America', '2022/10/17', 'default/not-found.png', '', 0), 
(29, 14, 'Floor Graphics', 'Retail and Consumer Goods', 'sample data', 'Walmart', '2025/07/29', 'default/not-found.png', '', 0), 
(30, 39, 'Interactive Displays', 'Energy and Utilities', 'sample data', 'Royal Dutch Shell', '2022/01/08', 'default/not-found.png', '', 0), 
(31, 7, 'Sponsored Maps', 'Healthcare and Pharmaceuticals', 'sample data', 'Johnson & Johnson', '2025/02/03', 'default/not-found.png', '', 0), 
(32, 33, 'Floor Graphics', 'Entertainment and Media', 'sample data', 'Walt Disney Company', '2028/05/09', 'default/not-found.png', '', 0), 
(33, 76, 'Branded Seats', 'Finance and Banking', 'sample data', 'Bank of America', '2023/04/22', 'default/not-found.png', '', 0), 
(34, 75, 'Handrails and Grab Straps', 'Aerospace and Defense', 'sample data', 'Boeing', '2030/12/17', 'default/not-found.png', '', 0), 
(35, 85, 'Digital Screens', 'Aerospace and Defense', 'sample data', 'Boeing', '2022/03/27', 'default/not-found.png', '', 0), 
(37, 28, 'Interactive Displays', 'Telecommunications', 'sample data', 'AT&T', '2029/03/31', 'default/not-found.png', '', 0), 
(38, 72, 'Digital Screens', 'Food and Beverage', 'sample data', 'McDonald', '2029/07/31', 'default/not-found.png', '', 0), 
(39, 22, 'Floor Graphics', 'Entertainment and Media', 'sample data', 'Walt Disney Company', '2030/10/27', 'default/not-found.png', '', 0), 
(41, 78, 'Branded Seats', 'Food and Beverage', 'sample data', 'PepsiCo', '2021/11/27', 'default/not-found.png', '', 0), 
(42, 57, 'Floor Graphics', 'Automotive and Transportation', 'sample data', 'Honda', '2020/04/09', 'default/not-found.png', '', 0), 
(43, 32, 'Floor Graphics', 'Healthcare and Pharmaceuticals', 'sample data', 'Pfizer', '2026/09/12', 'default/not-found.png', '', 0), 
(44, 71, 'Floor Graphics', 'Telecommunications', 'sample data', 'AT&T', '2022/11/13', 'default/not-found.png', '', 0), 
(45, 23, 'Sponsored Maps', 'Aerospace and Defense', 'sample data', 'Boeing', '2028/12/28', 'default/not-found.png', '', 0), 
(47, 96, 'Overhead Panels', 'Entertainment and Media', 'sample data', 'Walt Disney Company', '2023/10/18', 'default/not-found.png', '', 0), 
(48, 36, 'Digital Screens', 'Food and Beverage', 'sample data', 'PepsiCo', '2028/12/04', 'default/not-found.png', '', 0), 
(49, 92, 'Ceiling Ads', 'Finance and Banking', 'sample data', 'Bank of America', '2023/05/13', 'default/not-found.png', '', 0), 
(53, 19, 'Interactive Displays', 'Finance and Banking', 'sample data', 'JPMorgan Chase', '2024/02/03', 'default/not-found.png', '', 0), 
(58, 62, 'Branded Seats', 'Food and Beverage', 'sample data', 'PepsiCo', '2028/07/02', 'default/not-found.png', '', 0), 
(60, 45, 'Handrails and Grab Straps', 'Renewable Energy', 'sample data', 'Tesla', '2021/12/29', 'default/not-found.png', '', 0), 
(62, 59, 'Overhead Panels', 'Healthcare and Pharmaceuticals', 'sample data', 'Johnson & Johnson', '2027/08/10', 'default/not-found.png', '', 0), 
(66, 1, 'Window Graphics', 'Technology and Electronics', 'sample data', 'Alphabet', '2025/04/19', 'default/not-found.png', '', 0), 
(68, 66, 'Interactive Displays', 'Finance and Banking', 'sample data', 'Bank of America', '2030/06/12', 'default/not-found.png', '', 0), 
(69, 90, 'Interactive Displays', 'Retail and Consumer Goods', 'sample data', 'The Procter & Gamble Company', '2026/02/28', 'default/not-found.png', '', 0), 
(72, 31, 'Ceiling Ads', 'Finance and Banking', 'sample data', 'Bank of America', '2020/06/02', 'default/not-found.png', '', 0), 
(73, 64, 'Ceiling Ads', 'Aerospace and Defense', 'sample data', 'Boeing', '2026/07/18', 'default/not-found.png', '', 0), 
(74, 106, 'Sponsored Maps', 'Automotive and Transportation', 'sample data', 'General Motors', '2021/12/01', 'default/not-found.png', '', 0), 
(79, 108, 'Interior Posters', 'Energy and Utilities', 'sample data', 'Saudi Aramco', '2022/05/21', 'default/not-found.png', '', 0), 
(80, 110, 'Exterior Wrap Ads', 'Technology and Electronics', 'sample data', 'Apple', '2025/05/05', 'default/not-found.png', '', 0), 
(81, 111, 'Exterior Wrap Ads', 'Technology and Electronics', 'sample data', 'Facebook', '2024/06/24', 'default/not-found.png', '', 0);
