insert into spot (`id`, `type`, `station`, `spot_number`, `train`, `status`, `remark`) values 
(1, 'In_station', 'Back Bay', 'spot_0', '/', 'Occupied', ''), 
 (2, 'In_station', 'Back Bay', 'spot_1', '/', 'Occupied', ''), 
 (3, 'In_station', 'Back Bay', 'spot_2', '/', 'Available', ''), 
 (4, 'In_station', 'Back Bay', 'spot_3', '/', 'Available', ''), 
 (5, 'In_station', 'Back Bay', 'spot_4', '/', 'Available', ''), 
 (6, 'In_station', 'Back Bay', 'spot_5', '/', 'Available', ''), 
 (7, 'In_station', 'Back Bay', 'spot_6', '/', 'Occupied', ''), 
 (8, 'In_station', 'Back Bay', 'spot_7', '/', 'Available', ''), 
 (9, 'In_station', 'Back Bay', 'spot_8', '/', 'Available', ''), 
 (10, 'In_station', 'Jackson Square', 'spot_0', '/', 'Available', ''), 
 (11, 'In_station', 'Jackson Square', 'spot_1', '/', 'Occupied', ''), 
 (12, 'In_station', 'Jackson Square', 'spot_2', '/', 'Occupied', ''), 
 (13, 'In_station', 'Jackson Square', 'spot_3', '/', 'Occupied', ''), 
 (14, 'In_station', 'Jackson Square', 'spot_4', '/', 'Occupied', ''), 
 (15, 'In_station', 'Jackson Square', 'spot_5', '/', 'Available', ''), 
 (16, 'In_station', 'Jackson Square', 'spot_6', '/', 'Occupied', ''), 
 (17, 'In_station', 'Jackson Square', 'spot_7', '/', 'Occupied', ''), 
 (18, 'In_station', 'Jackson Square', 'spot_8', '/', 'Available', ''), 
 (19, 'In_station', 'Jackson Square', 'spot_9', '/', 'Occupied', ''), 
 (20, 'In_station', 'Jackson Square', 'spot_10', '/', 'Available', ''), 
 (21, 'In_station', 'Jackson Square', 'spot_11', '/', 'Occupied', ''), 
 (22, 'In_station', 'Jackson Square', 'spot_12', '/', 'Occupied', ''), 
 (23, 'In_station', 'Jackson Square', 'spot_13', '/', 'Occupied', ''), 
 (24, 'In_station', 'Jackson Square', 'spot_14', '/', 'Occupied', ''), 
 (25, 'In_station', 'Jackson Square', 'spot_15', '/', 'Available', ''), 
 (26, 'In_station', 'Stony Brook', 'spot_0', '/', 'Available', ''), 
 (27, 'In_station', 'Stony Brook', 'spot_1', '/', 'Available', ''), 
 (28, 'In_station', 'Stony Brook', 'spot_2', '/', 'Occupied', ''), 
 (29, 'In_station', 'Stony Brook', 'spot_3', '/', 'Occupied', ''), 
 (30, 'In_station', 'Stony Brook', 'spot_4', '/', 'Available', ''), 
 (31, 'In_station', 'Stony Brook', 'spot_5', '/', 'Occupied', ''), 
 (32, 'In_station', 'Stony Brook', 'spot_6', '/', 'Occupied', ''), 
 (33, 'In_station', 'Stony Brook', 'spot_7', '/', 'Occupied', ''), 
 (34, 'In_station', 'Stony Brook', 'spot_8', '/', 'Available', ''), 
 (35, 'In_station', 'Stony Brook', 'spot_9', '/', 'Occupied', ''), 
 (36, 'In_station', 'Stony Brook', 'spot_10', '/', 'Occupied', ''), 
 (37, 'In_station', 'Stony Brook', 'spot_11', '/', 'Available', ''), 
 (38, 'In_station', 'Stony Brook', 'spot_12', '/', 'Occupied', ''), 
 (39, 'In_station', 'Stony Brook', 'spot_13', '/', 'Occupied', ''), 
 (40, 'In_station', 'Stony Brook', 'spot_14', '/', 'Available', ''), 
 (41, 'In_station', 'Stony Brook', 'spot_15', '/', 'Occupied', ''), 
 (42, 'In_station', 'Stony Brook', 'spot_16', '/', 'Available', ''), 
 (43, 'In_station', 'Stony Brook', 'spot_17', '/', 'Available', ''), 
 (44, 'In_station', 'Stony Brook', 'spot_18', '/', 'Available', ''), 
 (45, 'In_station', 'Chinatown', 'spot_0', '/', 'Occupied', ''), 
 (46, 'In_station', 'Chinatown', 'spot_1', '/', 'Occupied', ''), 
 (47, 'In_station', 'Chinatown', 'spot_2', '/', 'Available', ''), 
 (48, 'In_station', 'Chinatown', 'spot_3', '/', 'Available', ''), 
 (49, 'In_station', 'Chinatown', 'spot_4', '/', 'Occupied', ''), 
 (50, 'In_station', 'Chinatown', 'spot_5', '/', 'Available', ''), 
 (51, 'In_station', 'Chinatown', 'spot_6', '/', 'Available', ''), 
 (52, 'In_station', 'Chinatown', 'spot_7', '/', 'Available', ''), 
 (53, 'In_station', 'Chinatown', 'spot_8', '/', 'Available', ''), 
 (54, 'In_station', 'Chinatown', 'spot_9', '/', 'Available', ''), 
 (55, 'In_station', 'Chinatown', 'spot_10', '/', 'Available', ''), 
 (56, 'In_station', 'Chinatown', 'spot_11', '/', 'Occupied', ''), 
 (57, 'In_station', 'Chinatown', 'spot_12', '/', 'Occupied', ''), 
 (58, 'In_station', 'Chinatown', 'spot_13', '/', 'Available', ''), 
 (59, 'In_station', 'Chinatown', 'spot_14', '/', 'Occupied', ''), 
 (60, 'In_station', 'North Station', 'spot_0', '/', 'Occupied', ''), 
 (61, 'In_station', 'North Station', 'spot_1', '/', 'Available', ''), 
 (62, 'In_station', 'North Station', 'spot_2', '/', 'Occupied', ''), 
 (63, 'In_station', 'North Station', 'spot_3', '/', 'Occupied', ''), 
 (64, 'In_station', 'North Station', 'spot_4', '/', 'Occupied', ''), 
 (65, 'In_station', 'North Station', 'spot_5', '/', 'Available', ''), 
 (66, 'In_station', 'North Station', 'spot_6', '/', 'Occupied', ''), 
 (67, 'In_station', 'Wellington', 'spot_0', '/', 'Available', ''), 
 (68, 'In_station', 'Wellington', 'spot_1', '/', 'Available', ''), 
 (69, 'In_station', 'Wellington', 'spot_2', '/', 'Occupied', ''), 
 (70, 'In_station', 'Wellington', 'spot_3', '/', 'Available', ''), 
 (71, 'In_station', 'Wellington', 'spot_4', '/', 'Occupied', ''), 
 (72, 'In_station', 'Wellington', 'spot_5', '/', 'Occupied', ''), 
 (73, 'In_station', 'Wellington', 'spot_6', '/', 'Available', ''), 
 (74, 'In_station', 'Wellington', 'spot_7', '/', 'Occupied', ''), 
 (75, 'In_station', 'Assembly', 'spot_0', '/', 'Occupied', ''), 
 (76, 'In_station', 'Assembly', 'spot_1', '/', 'Occupied', ''), 
 (77, 'In_station', 'Assembly', 'spot_2', '/', 'Available', ''), 
 (78, 'In_station', 'Assembly', 'spot_3', '/', 'Occupied', ''), 
 (79, 'In_station', 'Assembly', 'spot_4', '/', 'Available', ''), 
 (80, 'In_station', 'Assembly', 'spot_5', '/', 'Occupied', ''), 
 (81, 'In_station', 'Assembly', 'spot_6', '/', 'Available', ''), 
 (82, 'In_station', 'Ball Square', 'spot_0', '/', 'Available', ''), 
 (83, 'In_station', 'Ball Square', 'spot_1', '/', 'Occupied', ''), 
 (84, 'In_station', 'Ball Square', 'spot_2', '/', 'Available', ''), 
 (85, 'In_station', 'Ball Square', 'spot_3', '/', 'Occupied', ''), 
 (86, 'In_station', 'Ball Square', 'spot_4', '/', 'Available', ''), 
 (87, 'In_station', 'Ball Square', 'spot_5', '/', 'Occupied', ''), 
 (88, 'In_station', 'Arlington', 'spot_0', '/', 'Available', ''), 
 (89, 'In_station', 'Arlington', 'spot_1', '/', 'Occupied', ''), 
 (90, 'In_station', 'Arlington', 'spot_2', '/', 'Occupied', ''), 
 (91, 'In_station', 'Arlington', 'spot_3', '/', 'Occupied', ''), 
 (92, 'In_station', 'Arlington', 'spot_4', '/', 'Occupied', ''), 
 (93, 'In_station', 'Arlington', 'spot_5', '/', 'Available', ''), 
 (94, 'In_station', 'Arlington', 'spot_6', '/', 'Available', ''), 
 (95, 'In_station', 'Arlington', 'spot_7', '/', 'Available', ''), 
 (96, 'In_station', 'Arlington', 'spot_8', '/', 'Occupied', ''), 
 (97, 'In_station', 'Arlington', 'spot_9', '/', 'Available', ''), 
 (98, 'In_station', 'Arlington', 'spot_10', '/', 'Available', ''), 
 (99, 'In_station', 'Arlington', 'spot_11', '/', 'Available', ''), 
 (100, 'In_station', 'Kenmore', 'spot_0', '/', 'Occupied', ''), 
 (101, 'In_station', 'Kenmore', 'spot_1', '/', 'Available', ''), 
 (102, 'In_station', 'Kenmore', 'spot_2', '/', 'Available', ''), 
 (103, 'In_station', 'Kenmore', 'spot_3', '/', 'Available', ''), 
 (104, 'In_station', 'Kenmore', 'spot_4', '/', 'Available', ''), 
 (105, 'In_station', 'Kenmore', 'spot_5', '/', 'Available', ''), 
 (106, 'In_station', 'Kenmore', 'spot_6', '/', 'Occupied', ''), 
 (107, 'In_station', 'Kenmore', 'spot_7', '/', 'Available', ''), 
 (108, 'In_train', '/', '/', 'Orange Line', 'Occupied', ''), 
 (109, 'In_train', '/', '/', 'Green Line', 'Available', ''), 
 (110, 'In_train', '/', '/', 'Blue Line', 'Occupied', ''), 
 (111, 'In_train', '/', '/', 'Purple Line', 'Occupied', ''), 
 (112, 'In_train', '/', '/', 'Red Line', 'Available', '');
 